version: '3'
services:  
  ghost:
    image: ghost:latest
    volumes:
      - ./content:/var/lib/ghost
    ports:
      - 2368:2368
  buster:
    image: unsettling/buster:latest
    build:
      context: ./buster
      dockerfile: Dockerfile
    command: /buster.sh
    volumes:
      - ./static:/static
      - ./buster.sh:/buster.sh
  preview:
    image: nginx:alpine
    volumes:
      - ./static:/usr/share/nginx/html:ro
    ports:
      - 2369:80
